/**
 * Merging Religion's entry-file sections into a file the project already had.
 *
 * A repository that already carries agent instructions is the normal case, not the odd one,
 * and the previous behaviour left those installs with the workflow on disk but nothing
 * telling the agent it existed. Overwriting was never an option: those files are often the
 * most carefully written thing in the repository.
 *
 * So the user's file stays exactly where it is and Religion's sections are appended inside
 * markers. The markers are what make the result maintainable rather than a one-time paste:
 * a later update replaces what is between them and never reads what is outside.
 *
 * Two sections are deliberately left outside the block. "What this is" is what the user's own
 * file already says, and Commands is filled in by the setup skill with the project's real
 * commands. Both would be destroyed by an update that replaced them.
 */

export const MANAGED_START = "<!-- religion:managed:start -->";
export const MANAGED_END = "<!-- religion:managed:end -->";

/** Sections the user owns. They never enter the managed block. */
const USER_OWNED = new Set(["What this is", "Commands"]);

const BLOCK_NOTE =
  "Everything between these markers is generated by Religion and replaced on update.\n" +
  "Edit the files it points at, or the sections outside this block, rather than editing here.";

interface Section {
  heading: string;
  body: string;
}

/** Split a rendered entry file into its leading lines and its `## ` sections. */
function parse(entry: string): { lead: string[]; sections: Section[] } {
  const lines = entry.split(/\r?\n/);
  const lead: string[] = [];
  const sections: Section[] = [];
  let current: Section | null = null;

  for (const line of lines) {
    const heading = /^## (.+)$/.exec(line);
    if (heading?.[1]) {
      current = { heading: heading[1].trim(), body: "" };
      sections.push(current);
      continue;
    }
    if (current) current.body += line + "\n";
    else lead.push(line);
  }

  return { lead, sections };
}

function render(sections: readonly Section[]): string {
  return sections.map((s) => `## ${s.heading}\n${s.body.replace(/\n+$/, "")}\n`).join("\n");
}

/**
 * The part of a rendered entry file that Religion owns.
 *
 * Includes the import lines, which is what makes a merged install keep receiving new context
 * files: leaving them outside the block would freeze the set of loaded files at whatever
 * shipped on the day of the merge.
 */
export function managedBlock(templateEntry: string): string {
  const { lead, sections } = parse(templateEntry);
  const imports = lead.filter((line) => line.startsWith("@")).join("\n");
  const owned = sections.filter((s) => !USER_OWNED.has(s.heading));

  return [
    MANAGED_START,
    "",
    BLOCK_NOTE,
    "",
    ...(imports ? [imports, ""] : []),
    render(owned).replace(/\n+$/, ""),
    "",
    MANAGED_END
  ].join("\n");
}

/** The sections the user owns, taken from the template as a starting point. */
export function userOwnedSections(templateEntry: string): string {
  const { sections } = parse(templateEntry);
  const owned = sections.filter((s) => USER_OWNED.has(s.heading) && s.heading !== "What this is");
  return render(owned).replace(/\n+$/, "");
}

export function hasMarkers(contents: string): boolean {
  return contents.includes(MANAGED_START) && contents.includes(MANAGED_END);
}

/**
 * A file carrying one marker but not both, or them in the wrong order.
 *
 * This must be told apart from a file that was never merged. Treating it as unmerged splices
 * a second block into a file that already had one, which is a worse state than the damage it
 * was trying to repair.
 */
export function hasDamagedMarkers(contents: string): boolean {
  const start = contents.indexOf(MANAGED_START);
  const end = contents.indexOf(MANAGED_END);
  if (start < 0 && end < 0) return false;
  return start < 0 || end < 0 || end < start;
}

/**
 * Build the merged file: their content, then Religion's block, then the sections they own.
 *
 * Nothing of theirs moves. That is the property that makes this safe to accept without
 * reading the diff, and the reason the block is appended rather than woven in.
 */
export function spliceEntry(existing: string, templateEntry: string): string {
  const body = existing.replace(/\n+$/, "");
  const commands = userOwnedSections(templateEntry);
  const parts = [body, "", managedBlock(templateEntry)];
  // Only add Commands when their file has no section by that name; theirs is more accurate
  // than the placeholder, and setup will find either one.
  if (commands && !/^## Commands\s*$/m.test(existing)) parts.push("", commands);
  return parts.join("\n") + "\n";
}

/**
 * Replace the managed block in a merged file, leaving everything outside it untouched.
 *
 * Returns null when the markers are missing or out of order, which is treated as a conflict
 * rather than repaired: a file whose markers were edited is one whose owner had a reason.
 */
export function replaceManagedBlock(existing: string, templateEntry: string): string | null {
  const start = existing.indexOf(MANAGED_START);
  const end = existing.indexOf(MANAGED_END);
  if (start < 0 || end < 0 || end < start) return null;
  return existing.slice(0, start) + managedBlock(templateEntry) + existing.slice(end + MANAGED_END.length);
}
